# Generated by Django 4.0.6 on 2024-10-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectapp', '0002_alter_tasks_priority_alter_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Assigned_to',
            new_name='assigned_to',
        ),
    ]
