# Generated by Django 4.0.6 on 2024-10-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectapp', '0003_rename_assigned_to_tasks_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(db_column='task', on_delete=django.db.models.deletion.CASCADE, related_name='task_comment', to='userprojectapp.tasks'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='userprojectapp.user'),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='userprojectapp.projects'),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='userprojectapp.user'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_owner',
            field=models.ForeignKey(db_column='project_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to='userprojectapp.user'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='userprojectapp.user'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='userprojectapp.projects'),
        ),
    ]
